### ISSUE TITLE
"python setup.py test" failed on Ubuntu

### ISSUE THREAD

**Issue by cswhjiang** [piskvorky/gensim#241]
Here are the error messages:

running test
running egg_info
writing requirements to gensim.egg-info/requires.txt
writing gensim.egg-info/PKG-INFO
writing top-level names to gensim.egg-info/top_level.txt
writing dependency_links to gensim.egg-info/dependency_links.txt
reading manifest file 'gensim.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.sh' under directory '.'
writing manifest file 'gensim.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-i686-2.7/gensim/models/word2vec_inner.so -> gensim/models
Traceback (most recent call last):
  File "setup.py", line 155, in <module>
    include_package_data=True,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/jwh/program/gensim/gensim/__init__.py", line 6, in <module>
    from gensim import utils, matutils, interfaces, corpora, models, similarities
  File "/home/jwh/program/gensim/gensim/models/__init__.py", line 15, in <module>
    from .ldamulticore import LdaMulticore
  File "/home/jwh/program/gensim/gensim/models/ldamulticore.py", line 50, in <module>
    from gensim import utils
ImportError: cannot import name utils

Could anyone help me?

**Comment by tmylk** [comment]
Fixed
