### ISSUE TITLE
Numpy setup finalization is handled inconsistently

### ISSUE THREAD

**Issue by avanov** [piskvorky/gensim#250]
Hi!

I have been using gensim-0.8.9 until the recent moment, and when I decided to switch to 0.10.2, I have noticed that my deployment pipeline started failing because of inconsistent handling of numpy setup in [gensim's setup script](https://github.com/piskvorky/gensim/blob/develop/setup.py#L84).

Here is the tracelog of a standard installation process:
```
Downloading/unpacking numpy==1.9.0 (from -r /vagrant/projectx/configure/requirements.txt (line 167))
  http://pypi.projectx.domain/simple/numpy/1.9.0 uses an insecure transport scheme (http). Consider using https if pypi.projectx.domain has it available
  http://pypi.projectx.domain/simple/numpy/ uses an insecure transport scheme (http). Consider using https if pypi.projectx.domain has it available
  Running setup.py (path:/home/vagrant/pyenv/versions/latest-2/build/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking scipy==0.14.0 (from -r /vagrant/projectx/configure/requirements.txt (line 168))
  http://pypi.projectx.domain/simple/scipy/0.14.0 uses an insecure transport scheme (http). Consider using https if pypi.projectx.domain has it available
  http://pypi.projectx.domain/simple/scipy/ uses an insecure transport scheme (http). Consider using https if pypi.projectx.domain has it available
  Running setup.py (path:/home/vagrant/pyenv/versions/latest-2/build/scipy/setup.py) egg_info for package scipy
    
    warning: no previously-included files matching '*_subr_*.f' found under directory 'scipy/linalg/src/id_dist/src'
    no previously-included directories found matching 'scipy/special/tests/data/boost'
    no previously-included directories found matching 'scipy/special/tests/data/gsl'
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/generated'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
Downloading/unpacking gensim==0.10.2 (from -r /vagrant/projectx/configure/requirements.txt (line 169))
  http://pypi.projectx.domain/simple/gensim/0.10.2 uses an insecure transport scheme (http). Consider using https if pypi.projectx.domain has it available
  http://pypi.projectx.domain/simple/gensim/ uses an insecure transport scheme (http). Consider using https if pypi.projectx.domain has it available
  Running setup.py (path:/home/vagrant/pyenv/versions/latest-2/build/gensim/setup.py) egg_info for package gensim
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vagrant/pyenv/versions/latest-2/build/gensim/setup.py", line 155, in <module>
        include_package_data=True,
      File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 15, in replacement_run
      File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 193, in find_sources
      File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 277, in run
      File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 306, in add_defaults
      File "build/bdist.linux-x86_64/egg/setuptools/command/sdist.py", line 185, in add_defaults
      File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/home/vagrant/pyenv/versions/latest-2/build/gensim/setup.py", line 91, in finalize_options
        import numpy
    ImportError: No module named numpy
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/gensim.egg-info

writing requirements to pip-egg-info/gensim.egg-info/requires.txt

writing pip-egg-info/gensim.egg-info/PKG-INFO

writing top-level names to pip-egg-info/gensim.egg-info/top_level.txt

writing dependency_links to pip-egg-info/gensim.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/gensim.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/vagrant/pyenv/versions/latest-2/build/gensim/setup.py", line 155, in <module>

    include_package_data=True,

  File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 15, in replacement_run

  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 193, in find_sources

  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 277, in run

  File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 306, in add_defaults

  File "build/bdist.linux-x86_64/egg/setuptools/command/sdist.py", line 185, in add_defaults

  File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command

    cmd_obj.ensure_finalized()

  File "/home/vagrant/pyenv/versions/2.7.8/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/home/vagrant/pyenv/versions/latest-2/build/gensim/setup.py", line 91, in finalize_options

    import numpy

ImportError: No module named numpy

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/vagrant/pyenv/versions/latest-2/build/gensim
Storing debug log for failure in /home/vagrant/.pip/pip.log
```

It is important to note, that this error happens only when NumPy and gensim are installed at the same time, i.e. when pip is called with several packages as input parameters.

**Comment by tmylk** [comment]
Fixed in #251
