### ISSUE TITLE
TypeError: can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by heloowird** [piskvorky/gensim#290]
Traceback (most recent call last):
      File "D:\topic_model\word2vec\word2vec_test.py", line 17, in <module>
        word2vec = models.Word2Vec(clean_corpus, window=5, min_count=5)
      File "C:\Python27\lib\site-packages\gensim-0.10.3-py2.7-win-    amd64.egg\gensim\models\word2vec.py", line 312, in __init__
        self.build_vocab(sentences)
      File "C:\Python27\lib\site-packages\gensim-0.10.3-py2.7-win- amd64.egg\gensim\models\word2vec.py", line 414, in build_vocab
        self.reset_weights()
      File "C:\Python27\lib\site-packages\gensim-0.10.3-py2.7-win-amd64.egg\gensim\models\word2vec.py", line 521, in reset_weights
        random.seed(uint32(self.hashfxn(self.index2word[i] + str(self.seed))))
     TypeError: can only concatenate tuple (not "str") to tuple

**when updated gensim to 0.10.3, it happened.**

**Comment by piskvorky** [comment]
Looks like (some of) your input words in `clean_corpus` are tuples (should be strings).

**Comment by heloowird** [comment]
yes, tks !!
