### ISSUE TITLE
doc2vec training fails

### ISSUE THREAD

**Issue by piskvorky** [piskvorky/gensim#347]
Hello @gojomo ,

I tried training a doc2vec model, with

```python
model = Doc2Vec(dm=0, size=100, window=10, negative=5, hs=0, min_count=1, workers=1, seed=42)
model.build_vocab(all_docs)
model.train(all_docs)
```

but I'm getting the following exception (after which Python hangs):

```
2015-05-25 21:23:41,256 : MainThread : INFO : training model with 1 workers on 30456 vocabulary and 100 features, using 'skipgram'=1 'hierarchical softmax'=0 'subsample'=0 and 'negative sampling'=5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Volumes/work/workspace/gensim/trunk/gensim/models/word2vec.py", line 495, in worker_train
    job_words = self._get_job_words(alpha, work, job, neu1)
  File "/Volumes/work/workspace/gensim/trunk/gensim/models/doc2vec.py", line 418, in _get_job_words
    for sentence, (doclbl_indices, doclbl_vectors, ignored) in job)
  File "/Volumes/work/workspace/gensim/trunk/gensim/models/doc2vec.py", line 418, in <genexpr>
    for sentence, (doclbl_indices, doclbl_vectors, ignored) in job)
  File "gensimdevtemp/gensim/models/doc2vec_inner.pyx", line 319, in gensimdevtemp.gensim.models.doc2vec_inner.train_sentence_dbow (./gensim/models/doc2vec_inner.c:3334)
AttributeError: 'Doc2Vec' object has no attribute 'doclbl_syn0_lockf'
```

This is using the `develop` branch from your fork.

Any idea what's going on?

**Comment by gojomo** [comment]
Sorry, forgot to push the latest cython-compiled doc2vec_inner.c. It's there now. (Or, you should be able to do cython-compile doc2vec_inner.pyx and then do `python ./setup.py build_ext --inplace`.)

**Comment by piskvorky** [comment]
That did it, thanks!
