### ISSUE TITLE
MemoryError for LSI model

### ISSUE THREAD

**Issue by bluedesire** [piskvorky/gensim#378]
When trainning a LSI model with 116k articles, throws following exception:

Traceback (most recent call last):
  File "C:\Users\huan.wang\project\ArticleTagging\Trainning.py", line 49, in <module>
    lsi = models.LsiModel(corpus_tfidf, id2word=dictionary, num_topics=200)
  File "C:\Python27\lib\site-packages\gensim\models\lsimodel.py", line 331, in __init__
    self.add_documents(corpus)
  File "C:\Python27\lib\site-packages\gensim\models\lsimodel.py", line 388, in add_documents
    update = Projection(self.num_terms, self.num_topics, job, extra_dims=self.extra_samples, power_iters=self.power_iters)
  File "C:\Python27\lib\site-packages\gensim\models\lsimodel.py", line 126, in __init__
    extra_dims=self.extra_dims)
  File "C:\Python27\lib\site-packages\gensim\models\lsimodel.py", line 659, in stochastic_svd
    y = numpy.zeros(dtype=dtype, shape=(num_terms, samples))
MemoryError

I want to know the maximum capacity of corpus for LSI model in gensim? Since I use a small corpus(2k articles), everything seems fine.
How can I fix the problem?

**Comment by piskvorky** [comment]
There is no "maximum capacity", you're probably running into limitations of your machine.

Make sure you're running a 64bit Python, otherwise it cannot allocate much memory for you (even if you have the RAM physically). Plus, make sure you have enough RAM, of course.

Have a [look at the FAQ](https://github.com/piskvorky/gensim/wiki/Recipes-&-FAQ#q5-i-am-getting-out-of-memory-errors-with-lsi-how-much-memory-do-i-need) to see how much memory gensim requires for LSI.
