### ISSUE TITLE
Saving Doc2Vec Model -- SystemError: error return without exception set

### ISSUE THREAD

**Issue by ppotash** [piskvorky/gensim#403]
Using gensim 0.12.0 with python 2.6.

When I try to save a trained Doc2Vec model (roughly 8.4 millions tweets) by calling:

model.save('tdoc2vec_model_v0')
or
model.save('tdoc2vec_model_v0', ignore=['syn0norm', 'syn1'])
(honestly though I don't understand what the ignore attribute does)

I get the following error:

Traceback (most recent call last):
  File "tweets2vec.py", line 52, in <module>
    model.save('tdoc2vec_model_v0')
  File "/home/pota755/.virtualenvs/potash-e/lib/python2.6/site-packages/gensim-0.12.0-py2.6-linux-x86_64.egg/gensim/models/word2vec.py", line 1288, in save
    super(Word2Vec, self).save(*args, **kwargs)
  File "/home/pota755/.virtualenvs/potash-e/lib/python2.6/site-packages/gensim-0.12.0-py2.6-linux-x86_64.egg/gensim/utils.py", line 482, in save
    pickle_protocol=pickle_protocol)
  File "/home/pota755/.virtualenvs/potash-e/lib/python2.6/site-packages/gensim-0.12.0-py2.6-linux-x86_64.egg/gensim/utils.py", line 355, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "/home/pota755/.virtualenvs/potash-e/lib/python2.6/site-packages/gensim-0.12.0-py2.6-linux-x86_64.egg/gensim/utils.py", line 901, in pickle
    _pickle.dump(obj, fout, protocol=protocol)
SystemError: error return without exception set

This seems to be a similar issue as here:
https://github.com/piskvorky/gensim/issues/161
Was the save functionality you implemented supposed to deal with this error? Or is this more a problem with my python version? I've used h5py to save large numpy matrices before, but I don't know if it'll work with this type of object.

I trained a Word2Vec model and successfully saved the model (passing an open file to save. I never tried passing just a file name) on the same dataset (though I don't remember if that was with the pip installed version of gensim or cloned from github).

**Comment by gojomo** [comment]
Yes, this recursive SaveLoad isn't properly allowing the subcomponent a chance to save its oversized ndarray – so the pickle limit is being hit. There's a fix in 7f323fc in PR #393 .

**Comment by gojomo** [comment]
The fix is now in the develop branch and will be in the next release.
