### ISSUE TITLE
gensim install error 

### ISSUE THREAD

**Issue by dzhwinter** [piskvorky/gensim#575]
system: mac os EI caption
there is an similar issue here,   you  mentioned that there is an wrong version python package. I can't find it now. close this issue immedetaly is ok.

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 371, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 1] Operation not permitted: '/bin/asadmin'

```

**Comment by dzhwinter** [comment]
this can be resolved by install with sudo -H
e.g. "sudo -H pip install gensim" will work.  This because -H will set $HOME path for current user. you'd better change the owner of LIBRARY of pip and cache

**Comment by piskvorky** [comment]
This seems to be related to filesystem privileges. If you want to install to system-wide locations, you probably have to use `sudo`, yes.

Not sure what setting HOME (`sudo -H`) is for -- why do you need that?

The recommended practice in python is to use `virtualenv` (or `virtualenvwrapper`), to cleanly separate Python environments. The environments typically live in your home, so there's no need for `sudo`.

**Comment by dzhwinter** [comment]
setting -H flag seems crazy , but it’s works. actually install many packages such as pub, gensim only add -H will do the right thing, otherwise it complain about the permission problem. 
as we all know, when use sudo prefix, the command will transfer super authority to current user, maybe -H will set the dir for current user. I can’t explain it.  this only happen in OS X EICaption. 
 that’s why i open the issue there. Hope somebody will find the -H affect which permission.

**Comment by piskvorky** [comment]
Ok. Thanks for the tip @dzhwinter -- closing this now.

In case anyone hits this issue in the future -- virtualenv + pip are still the preferred solution for Python package installations, including gensim. System-wide root installs are not recommended, unless absolutely necessary.
