### ISSUE TITLE
ImportError: cannot import name utils

### ISSUE THREAD

**Issue by kklw** [piskvorky/gensim#623]
`from gensim.models import word2vec`

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.5\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Kavan Koh\sports_news_virenv\lib\site-packages\gensim\__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.5\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Kavan Koh\sports_news_virenv\lib\site-packages\gensim\matutils.py", line 17, in <module>
    from gensim import utils
ImportError: cannot import name utils

cannot find references six.moves in  matutils.py
`from six.moves import xrange, zip as izip`

pip list 
> boto (2.39.0)
> bz2file (0.98)
> gensim (0.12.4)
> httpretty (0.8.10)
> numpy (1.10.4)
> oauthlib (1.0.3)
> pip (8.0.3)
> requests (2.8.1)
> requests-oauthlib (0.6.1)
> scipy (0.17.0)
> setuptools (3.6)
> six (1.10.0)
> smart-open (1.3.2)

Running on windows 10. Project in a virtual env.

**Comment by piskvorky** [comment]
Can you paste the exact traceback, from when you do `from six.moves import xrange, zip as izip` in a clean Python shell?

**Comment by kklw** [comment]
Hi. No error when i do `from six.moves import xrange, zip as izip`. I stopped using anaconda as my base interpreter and downloaded the binaries from http://www.lfd.uci.edu/~gohlke/pythonlibs/ and it is working now. Thanks.

**Comment by piskvorky** [comment]
Oh ok. Thanks for reporting -- hopefully this will help someone in the future, if they google up this issue.
