### ISSUE TITLE
Import gensim failed after upgrade to XCode Version 7.3 (7D175)

### ISSUE THREAD

**Issue by galaxyh** [piskvorky/gensim#638]
Hi,

Before upgrading XCode to Version 7.3 (7D175), gensim works perfectly fine for me.
However, after the upgrade, I am not able to import gensim anymore.
For example, when executing <pre>python -c "import gensim"</pre> I get the following error:

<pre>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Steven/code/lib/python2.7/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "/Users/Steven/code/lib/python2.7/site-packages/gensim/corpora/__init__.py", line 18, in <module>
    from .sharded_corpus import ShardedCorpus
  File "/Users/Steven/code/lib/python2.7/site-packages/gensim/corpora/sharded_corpus.py", line 34, in <module>
    import theano
  File "/Users/Steven/code/lib/python2.7/site-packages/theano/__init__.py", line 63, in <module>
    from theano.compile import (
  File "/Users/Steven/code/lib/python2.7/site-packages/theano/compile/__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "/Users/Steven/code/lib/python2.7/site-packages/theano/compile/function_module.py", line 22, in <module>
    import theano.compile.mode
  File "/Users/Steven/code/lib/python2.7/site-packages/theano/compile/mode.py", line 12, in <module>
    import theano.gof.vm
  File "/Users/Steven/code/lib/python2.7/site-packages/theano/gof/vm.py", line 638, in <module>
    from . import lazylinker_c
  File "/Users/Steven/code/lib/python2.7/site-packages/theano/gof/lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "/Users/Steven/code/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2196, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sse4a'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-tbm'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-fma4'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-prfchw'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-rtm'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-rdseed'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-hle'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sha'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: no such file or directory: '+cx16'. clang: error: no such file or directory: '+xsave'. clang: error: no such file or directory: '+bmi2'. clang: error: language not recognized: 'savec'. clang: error: no such file or directory: '+fsgsbase'. clang: error: no such file or directory: '+avx'. clang: error: no such file or directory: '+popcnt'. clang: error: no such file or directory: '+fma'. clang: error: no such file or directory: '+bmi'. clang: error: no such file or directory: '+aes'. clang: error: no such file or directory: '+rdrnd'. clang: error: language not recognized: 'saves'. clang: error: no such file or directory: '+sse4.1'. clang: error: no such file or directory: '+sse4.2'. clang: error: no such file or directory: '+avx2'. clang: error: no such file or directory: '+sse'. clang: error: no such file or directory: '+lzcnt'. clang: error: no such file or directory: '+pclmul'. clang: error: no such file or directory: '+f16c'. clang: error: no such file or directory: '+ssse3'. clang: error: no such file or directory: '+mmx'. clang: error: no such file or directory: '+cmov'. clang: error: language not recognized: 'op'. clang: error: no such file or directory: '+movbe'. clang: error: no such file or directory: '+xsaveopt'. clang: error: no such file or directory: '+sse2'. clang: error: no such file or directory: '+sse3'.</pre>

Does anybody know how to fix this?
Thanks a lot.

**Comment by galaxyh** [comment]
Sorry. I found the problem comes from Theano, not gensim.
