### ISSUE TITLE
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

### ISSUE THREAD

**Issue by GSingh2014** [piskvorky/gensim#661]
OS X 10.10.5
Python 3.5
gensim 0.12.4

Running the saved LDAMallet model on new documents is giving the error
2016-04-06 11:33:47,410 : INFO : **loading Dictionary object from /gensim_Mallet/gensim_Mallet_LDA.dict**
2016-04-06 11:33:47,411 : **INFO : loading LdaMallet object from /gensim_Mallet/gensim_Mallet_LDA.model**
2016-04-06 11:33:47,411 : INFO : loading id2word recursively from /gensim_Mallet/gensim_Mallet_LDA.model.id2word.* with mmap=None
bow created
[(0, 5), (3, 8), (7, 99), (9, 6), (14, 1), (22, 1), (60, 3), (79, 1), (80, 1), (121, 3), (163, 2), (189, 1), (204, 6), (210, 5), (214, 6), (215, 5793)]
2016-04-06 11:33:47,424 : INFO : serializing temporary corpus to /var/folders/50/dx53qks96x54d05lq4l5mqxr0000gn/T/134f2a_corpus.txt
2016-04-06 11:33:47,425 : INFO : converting temporary corpus to MALLET format with /usr/local/Cellar/mallet-2.0.6/bin/mallet import-file --preserve-case --keep-sequence --remove-stopwords --token-regex '\S+' --input /var/folders/50/dx53qks96x54d05lq4l5mqxr0000gn/T/134f2a_corpus.txt --output /var/folders/50/dx53qks96x54d05lq4l5mqxr0000gn/T/134f2a_corpus.mallet.infer --use-pipe-from /var/folders/50/dx53qks96x54d05lq4l5mqxr0000gn/T/134f2a_corpus.mallet
2016-04-06 11:33:47,894 : INFO : inferring topics with MALLET LDA '/usr/local/Cellar/mallet-2.0.6/bin/mallet infer-topics --input /var/folders/50/dx53qks96x54d05lq4l5mqxr0000gn/T/134f2a_corpus.mallet.infer --inferencer /var/folders/50/dx53qks96x54d05lq4l5mqxr0000gn/T/134f2a_inferencer.mallet --output-doc-topics /var/folders/50/dx53qks96x54d05lq4l5mqxr0000gn/T/134f2a_doctopics.txt.infer --num-iterations 100'
Traceback (most recent call last):
  File "/Py/LDAGensim_Mallet_Apply.py", line 60, in <module>
    **print(ldamodel[bow])**
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gensim/models/wrappers/ldamallet.py", line 173, in __getitem__
    **result = list(self.read_doctopics(self.fdoctopics() + '.infer'))**
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/gensim/models/wrappers/ldamallet.py", line 254, in read_doctopics
    **if lineno == 0 and line.startswith("#doc "):**
**TypeError: startswith first arg must be bytes or a tuple of bytes, not str**

My code is as follows:

utilDoc = utils.simple_preprocess(cleandocument)
tokens = [bytes(word,'utf-8') for word in utilDoc if word not in mystopwords]

modeldict = gensim.corpora.Dictionary.load('/gensim_Mallet/gensim_Mallet_LDA.dict')
ldamodel = models.wrappers.ldamallet.LdaMallet.load('/gensim_Mallet/gensim_Mallet_LDA.model')

bow = modeldict.doc2bow(tokens)
print("bow created")
print(bow)

print(ldamodel[bow])

**Comment by tmylk** [comment]
Fixed in #702
