### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by tengpeng** [piskvorky/gensim#670]
```
[pt@centos7 gensim]$ /bin/python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gensim
RuntimeError: module compiled against API version a but this version of numpy is 7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
  File "gensim/parsing/__init__.py", line 7, in <module>
    from .preprocessing import *
  File "gensim/parsing/preprocessing.py", line 10, in <module>
    from gensim import utils
  File "gensim/utils.py", line 40, in <module>
    import scipy.sparse
  File "/usr/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 214, in <module>
    from .csr import *
  File "/usr/lib/python2.7/site-packages/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: numpy.core.multiarray failed to import
```

**Comment by tengpeng** [comment]
```
>>> import numpy; numpy.show_config()
lapack_info:
    libraries = ['lapack']
    library_dirs = ['/usr/lib64']
    language = f77
atlas_threads_info:
    libraries = ['atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('ATLAS_WITHOUT_LAPACK', None)]
    language = c
    include_dirs = ['/usr/include']
blas_opt_info:
    libraries = ['atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('ATLAS_INFO', '"\\"3.10.1\\""')]
    language = c
    include_dirs = ['/usr/include']
atlas_blas_threads_info:
    libraries = ['atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('ATLAS_INFO', '"\\"3.10.1\\""')]
    language = c
    include_dirs = ['/usr/include']
lapack_opt_info:
    libraries = ['tatlas', 'lapack']
    library_dirs = ['/usr/lib64/atlas', '/usr/lib64']
    define_macros = [('ATLAS_WITHOUT_LAPACK', None)]
    language = f77
    include_dirs = ['/usr/include']
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE

>>> import scipy; scipy.show_config()
atlas_3_10_blas_threads_info:
    libraries = ['atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
    language = c
    include_dirs = ['/usr/include']
lapack_opt_info:
    libraries = ['tatlas', 'tatlas', 'atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('NO_ATLAS_INFO', -1)]
    language = f77
    include_dirs = ['/usr/include']
blas_opt_info:
    libraries = ['atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
    language = c
    include_dirs = ['/usr/include']
openblas_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
    libraries = ['tatlas', 'tatlas', 'atlas']
    library_dirs = ['/usr/lib64/atlas']
    define_macros = [('NO_ATLAS_INFO', -1)]
    language = f77
    include_dirs = ['/usr/include']
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
mkl_info:
  NOT AVAILABLE
```

**Comment by tmylk** [comment]
Which version of gensim are you using? Are you using anaconda or virtualenv?

**Comment by tengpeng** [comment]
I figured out the problem is due to incomplete installation of `Scipy`. On a fresh CentOS, two dependency of `Scipy` should be installed by hand.
