### ISSUE TITLE
key error in doc2vec

### ISSUE THREAD

**Issue by ziaoang** [piskvorky/gensim#685]
Hi,
I want to train a sentence to a vector, so I try to use doc2vec, but it seems wrong.

```
from gensim.models.doc2vec import TaggedDocument
from gensim.models import Doc2Vec

sentences = []
sentence = TaggedDocument(words=['some', 'words', 'here'], tags=['SENT_1'])
sentences.append(sentence)

model = Doc2Vec(sentences, size=10, window=8, min_count=0, workers=4)

print(model["some"])
print(model["words"])
print(model["here"])
print(model["SENT_1"])
```

the output is
```
[-0.01763519 -0.02702416 -0.0479279   0.0318843   0.00628794  0.01604467
 -0.00856361  0.01754908  0.04984165 -0.00911445]
[-0.03017868 -0.02489978  0.00481066 -0.00926726 -0.04562107 -0.03806574
 -0.0037596   0.00202511 -0.04629255 -0.04483321]
[-0.03189216 -0.0110036  -0.00566302 -0.02581468  0.01591296 -0.01258255
  0.02523786  0.03190928 -0.00576188 -0.00726446]
Traceback (most recent call last):
  File "use.py", line 13, in <module>
    print(model["SENT_1"])
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 1318, in __getitem__
    return self.syn0[self.vocab[words].index]
KeyError: 'SENT_1'
```

It seems I just get the word2vec, not the doc2vec.

Best.

**Comment by gojomo** [comment]
Doc vectors are accessed via the 'docvecs' component of the model:

    print(model.docvecs['SENT_1'])
